version: '3.8'

services:
  node_backend:
    container_name: node_1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./src:/app/src
      - ./.docker.env:/app/.env
    networks:
      - backend_net
    depends_on:
      - mongo_db

  mongo_db:
    container_name: db_1
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend_net

networks:
  backend_net:
    driver: "bridge"
